version: '3.8'

services:
  med_voll_db_postgres:
    restart: always
    image: postgres:13-alpine
    container_name: med_voll_db_postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=${PSQL_SERVICO_USER:?error}
      - POSTGRES_PASSWORD=${PSQL_SERVICO_PASS:?error}
      - POSTGRES_DB=${PSQL_DATABASE:?error}
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "5440:5432"
    networks:
      - med-voll-network

  med-voll-backend:
    build: med-voll-backend/docker
    image: amazoncorretto:17.0.7-alpine
    container_name: med-voll-backend
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORTA_API_BACKEND=${PORTA_API_BACKEND}
      - PORTA_API_SECURITY=${PORTA_API_SECURITY}
      - GOOGLE_RECAPTCHA_KEY_SITE=${GOOGLE_RECAPTCHA_KEY}
      - GOOGLE_RECAPTCHA_SECRET_KEY=${GOOGLE_RECAPTCHA_SECRET}
      - MAIL_USERNAME=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_SENHA}
      - PSQL_SERVER=med_voll_db_postgres
      - PSQL_SERVER_PORT=5432
      - PSQL_DATABASE=${PSQL_DATABASE:?error}
      - PSQL_SERVICO_USERNAME=${PSQL_SERVICO_USER:?error}
      - PSQL_SERVICO_PASSWORD=${PSQL_SERVICO_PASS:?error}
    ports:
      - "${PORTA_API_BACKEND}:${PORTA_API_BACKEND}"
    depends_on:
      #- med-voll-security
      - med_voll_db_postgres
    entrypoint: ["sh", "/usr/local/bin/wait-for-it", "med_voll_db_postgres:5432", "--", "java", "-jar", "/opt/java/app.jar"]
    networks:
      - med-voll-network
    volumes:
      - ./med-voll-backend/target/med-voll-backend.jar:/opt/java/app.jar

networks:
  med-voll-network:
    driver: bridge

volumes:
  postgres-data:


