version: '3.8'

services:
  med_voll_db_postgres:
    restart: always
    image: postgres:13-alpine
    container_name: med_voll_db_postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=${PSQL_SERVICO_USER:?error}
      - POSTGRES_PASSWORD=${PSQL_SERVICO_PASS:?error}
      - POSTGRES_DB=${PSQL_DATABASE:?error}
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "5440:5432"
    networks:
      - med-voll-network

  med-voll-backend:
    build: ./docker
    image: amazoncorretto:17.0.7-alpine
    container_name: med-voll-backend
    environment:
      - PORTA_API=9091
      - PSQL_SERVER=med_voll_db_postgres
      - PSQL_SERVER_PORT=5432
      - PSQL_DATABASE=${PSQL_DATABASE:?error}
      - PSQL_SERVICO_USERNAME=${PSQL_SERVICO_USER:?error}
      - PSQL_SERVICO_PASSWORD=${PSQL_SERVICO_PASS:?error}
    ports:
      - "9091:8080"
    depends_on:
      - med_voll_db_postgres
    entrypoint: ["sh", "/usr/local/bin/wait-for-it", "med_voll_db_postgres:5432", "--", "java", "-jar", "/opt/java/app.jar"]
    networks:
      - med-voll-network
    volumes:
      - ./target/med.voll.jar:/opt/java/app.jar

networks:
  med-voll-network:
    driver: bridge

volumes:
  postgres-data:


