drop table if exists tb_consulta_medica cascade;
drop table if exists tb_medico cascade;
drop table if exists tb_paciente cascade;
drop table if exists tb_paciente cascade;
drop table if exists tb_pessoa cascade;
drop table if exists tb_pessoa cascade;

create table tb_consulta_medica (
        dt_consulta timestamp(6) not null,
        id_consulta_medica bigint not null,
        primary key (id_consulta_medica)
    );

create table tb_medico (
        id_pessoa bigint not null,
        crm varchar(255),
        in_especialidade varchar(255) check (in_especialidade in ('ORTOPEDIA', 'CARDIOLOGIA', 'NEUROLOGIA', 'DERMATOLOGIA', 'PEDIATRIA')),
        primary key (id_pessoa)
    );

create table tb_paciente (
        id_pessoa bigint not null,
        profissao varchar(255),
        primary key (id_pessoa)
    );

create table tb_pessoa (
        id_pessoa bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        cpf varchar(255) not null unique,
        email varchar(255) not null,
        logradouro varchar(255),
        nome varchar(255),
        numero varchar(255),
        uf varchar(255),
        primary key (id_pessoa),
        unique (cpf, nome)
    );

alter table if exists tb_medico
       add constraint fk01_tb_medico
       foreign key (id_pessoa) 
       references tb_pessoa;

alter table if exists tb_paciente
       add constraint fk01_tb_paciente
       foreign key (id_pessoa) 
       references tb_pessoa;